# Generated by Django 6.0 on 2026-01-05 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.ImageField(default=0, upload_to='')),
                ('zipcode', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('Koshi', 'Koshi Pradesh'), ('Madhesh', 'Madhesh Pradesh'), ('Bagmati', 'Bagmati Pradesh'), ('Gandaki', 'Gandaki Pradesh'), ('Lumbini', 'Lumbini Pradesh'), ('Karnali', 'Karnali Pradesh'), ('Sudurpashchim', 'Sudurpashchim Pradesh')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
