# Generated by Django 4.2.8 on 2026-02-25 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_farmer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_purchases', models.FloatField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('BRONZE', 'Bronze Tier'), ('SILVER', 'Silver Tier'), ('GOLD', 'Gold Tier'), ('PLATINUM', 'Platinum Tier')], max_length=20, unique=True)),
                ('min_points', models.IntegerField(default=0)),
                ('max_points', models.IntegerField(default=9999999)),
                ('bonus_multiplier', models.FloatField(default=1.0)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#999999', max_length=20)),
                ('icon_emoji', models.CharField(default='⭐', max_length=5)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Points Earned'), ('REDEEM', 'Points Redeemed'), ('BONUS', 'Bonus Points'), ('EXPIRE', 'Points Expired')], max_length=10)),
                ('points', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.customerloyalty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('FREEPRODUCT', 'Free Product'), ('SHIPPING', 'Free Shipping'), ('UPGRADE', 'Subscription Upgrade')], max_length=20)),
                ('points_required', models.IntegerField()),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='RedeemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_rewards', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderplaced')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reward')),
            ],
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.loyaltytier'),
        ),
        migrations.AddField(
            model_name='customerloyalty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL),
        ),
    ]
