# Generated by Django 4.2.8 on 2026-02-27 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customerloyalty_loyaltytier_rewardtransaction_reward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to qualify')),
                ('discount_percentage', models.FloatField(help_text='Discount percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_discounts', to='app.product')),
            ],
            options={
                'ordering': ['product', 'min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
